language: java

jdk:
  - openjdk8

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout -qfb $TRAVIS_BRANCH $TRAVIS_COMMIT

script:
  - ./gradlew versionDisplay versionFile build --stacktrace --console plain

# TODO GitHub release for release branches
