language: java

jdk:
  - openjdk8

script:
  - ./gradlew versionDisplay versionFile build --stacktrace --console plain

# TODO GitHub release for release branches
# TODO Full clone:
#install:
#  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
#  - cd $TRAVIS_REPO_SLUG
#  - git checkout -qf $TRAVIS_COMMIT
